### ISSUE TITLE
Crash on join

### ISSUE THREAD

**Issue by Diamondman121314** [Siphalor/tweed-api#6]
When joining a world, right after preparing the spawn area, it seems to crash the client, but freezes at that point so it never really creates an entire crash report.
https://gist.github.com/Diamondman121314/434ab9f689b4a348301ce66c9f88c2e0

EDIT: It seems as it is Bouncy Life causing the crash.

**Comment by Siphalor** [comment]
Do you have Extra Pieces (>= 2.0.0) installed?

**Comment by Diamondman121314** [comment]
Yes, and as of right now I have 2.2.6, the latest available.

I seem to now crash with a different error from both MouseWheelie and BouncyLife.
[MouseWheelie Crash](https://gist.github.com/Diamondman121314/6febbe496b16e59fb567bc65d048ca12#file-gistfile1-txt-L804)
[BouncyLife Crash](https://gist.github.com/Diamondman121314/c58639d7dd4293689a19335c73aed7d8#file-gistfile1-txt-L800)

**Comment by Siphalor** [comment]
These crashes basically mean that Tweed wasn't loaded what basically shouldn't be possible.
The conflict with EP is fixed so this seems to be a loader glitch.

**Possible steps to fix:**
Please try to delete your `.fabric` and `.mixin.out` folders and rerun the game.
If that doesn't work you may want to create a fresh minecraft fabric instance.

**Comment by Diamondman121314** [comment]
It seems as it still crashes, but this is before it all loads.
https://gist.github.com/Diamondman121314/f7f8a78335f73fd5da9546aaeeeee6e3

**Comment by Siphalor** [comment]
That's not my fault anymore. Try to clean both folders again and/or make a new instance.

**Comment by Diamondman121314** [comment]
I went as far as to download the develop of MultiMC and put it in a difference place from my original, because I needed to fix my original anyway. It seems as that same crash happens. Should I make an issue for this on Extra Pieces?

**Comment by Diamondman121314** [comment]
I downloaded Tweed as a jar file (2.2.2) and it seems as that fixed it, though I'm not sure if that should be done, but with that, I got the original error that started this, the onGameJoin Mixin crash when joining a world.

https://gist.github.com/Diamondman121314/bd24e66d000ec9d97ef488bdc06986f6#file-gistfile1-txt-L348

**Comment by Siphalor** [comment]
Where did you download Tweed 2.2.2 from?

**Comment by Diamondman121314** [comment]
I just looked at the build.gradle of Tweed and got it from JitPack.

**Comment by Siphalor** [comment]
I just checked EP and the cause for the crash with no explanation seems to be that it directly denies Tweed beginning from 2.2.5.

So I'm going to track that Mixin bug down via 2.2.4

**Comment by Diamondman121314** [comment]
Yeah, I removed the break part from the fabric.mod.json so I could test if the latest of each worked together.

**Comment by Siphalor** [comment]
I guess I could "fix" that issue.
The problem seems to be that somehow the fabric loader/mixin library decides to apply the mixin twice. So if I allow the mixin to fail this bug disappears. :/

So far so good but this would make it possible that Tweed silently fails and noone notices it.

**Comment by Siphalor** [comment]
Wait a moment - I think I've got the final solution.

I'll run some tests now and then contact Shnupbups so he knows that the conflict is solved.

**Comment by Siphalor** [comment]
This is killing me. I'll try it tomorrow again...

**Comment by Siphalor** [comment]
There's now this: FabricMC/fabric-loader#140.

**Temporary workaround: Use Tweed or Artifice as a normal mod beneath MW and EP.**

**Comment by Siphalor** [comment]
It's finally fixed 😭

One f*cking line of code (btw the issue is on both ends - Tweed and Artifice).
